# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'original_design\nova_carga.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NovaCarga(object):
    def setupUi(self, NovaCarga):
        NovaCarga.setObjectName("NovaCarga")
        NovaCarga.resize(565, 379)
        self.groupBox = QtWidgets.QGroupBox(NovaCarga)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 541, 81))
        self.groupBox.setObjectName("groupBox")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 20, 361, 16))
        self.label_5.setObjectName("label_5")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 40, 521, 31))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.carga_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.carga_label.setObjectName("carga_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.carga_label)
        self.carga_nome = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.carga_nome.setObjectName("carga_nome")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.carga_nome)
        self.groupBox_2 = QtWidgets.QGroupBox(NovaCarga)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 100, 541, 221))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 521, 181))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.equipList = QtWidgets.QListWidget(self.horizontalLayoutWidget_2)
        self.equipList.setObjectName("equipList")
        self.horizontalLayout_2.addWidget(self.equipList)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.addOne = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.addOne.setObjectName("addOne")
        self.verticalLayout_2.addWidget(self.addOne)
        self.addMany = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.addMany.setObjectName("addMany")
        self.verticalLayout_2.addWidget(self.addMany)
        self.equipNum = QtWidgets.QSpinBox(self.horizontalLayoutWidget_2)
        self.equipNum.setMinimum(1)
        self.equipNum.setMaximum(100)
        self.equipNum.setProperty("value", 10)
        self.equipNum.setObjectName("equipNum")
        self.verticalLayout_2.addWidget(self.equipNum)
        self.removeEquip = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.removeEquip.setObjectName("removeEquip")
        self.verticalLayout_2.addWidget(self.removeEquip)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.addedEquipList = QtWidgets.QListWidget(self.horizontalLayoutWidget_2)
        self.addedEquipList.setObjectName("addedEquipList")
        self.horizontalLayout_2.addWidget(self.addedEquipList)
        self.line = QtWidgets.QFrame(NovaCarga)
        self.line.setGeometry(QtCore.QRect(10, 320, 541, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.buttonBox = QtWidgets.QDialogButtonBox(NovaCarga)
        self.buttonBox.setGeometry(QtCore.QRect(210, 340, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok
        )
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(NovaCarga)
        QtCore.QMetaObject.connectSlotsByName(NovaCarga)

    def retranslateUi(self, NovaCarga):
        _translate = QtCore.QCoreApplication.translate
        NovaCarga.setWindowTitle(_translate("NovaCarga", "Carga"))
        self.groupBox.setTitle(_translate("NovaCarga", "Carga"))
        self.label_5.setText(
            _translate(
                "NovaCarga", "Conjunto de equipamentos que constituem um consumidor"
            )
        )
        self.carga_label.setText(_translate("NovaCarga", "Nome"))
        self.groupBox_2.setTitle(_translate("NovaCarga", "Adicionar Equipamentos"))
        self.addOne.setText(_translate("NovaCarga", ">"))
        self.addMany.setText(_translate("NovaCarga", ">>"))
        self.removeEquip.setText(_translate("NovaCarga", "Remover"))
