# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\equipamentoMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MenuEquipamento(object):
    def setupUi(self, MenuEquipamento):
        MenuEquipamento.setObjectName("MenuEquipamento")
        MenuEquipamento.resize(400, 300)
        self.verticalLayoutWidget = QtWidgets.QWidget(MenuEquipamento)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 381, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.equipamentoLista = QtWidgets.QListView(self.verticalLayoutWidget)
        self.equipamentoLista.setObjectName("equipamentoLista")
        self.verticalLayout.addWidget(self.equipamentoLista)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.EditarEquipamento = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.EditarEquipamento.setObjectName("EditarEquipamento")
        self.horizontalLayout.addWidget(self.EditarEquipamento)
        self.NovoEquipamento = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.NovoEquipamento.setObjectName("NovoEquipamento")
        self.horizontalLayout.addWidget(self.NovoEquipamento)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(MenuEquipamento)
        QtCore.QMetaObject.connectSlotsByName(MenuEquipamento)

    def retranslateUi(self, MenuEquipamento):
        _translate = QtCore.QCoreApplication.translate
        MenuEquipamento.setWindowTitle(_translate("MenuEquipamento", "Equipamentos"))
        self.EditarEquipamento.setText(_translate("MenuEquipamento", "Editar"))
        self.NovoEquipamento.setText(_translate("MenuEquipamento", "Criar Novo"))
