# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\novo_equipamento.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QWidget


class EquipamentoWindow(QWidget):
    """
    This "window" is a QWidget. If it has no parent, it
    will appear as a free-floating window as we want.
    """

    def __init__(self, parent):
        super().__init__()
        self.setupUi(self)
        self.service = parent.service

    def setupUi(self, NovoEquipamento):
        NovoEquipamento.setObjectName("NovoEquipamento")
        NovoEquipamento.resize(500, 251)
        self.groupBox = QtWidgets.QGroupBox(NovoEquipamento)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 480, 41))
        self.groupBox.setObjectName("groupBox")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(20, 20, 480, 16))
        self.label_5.setObjectName("label_5")
        self.groupBox_2 = QtWidgets.QGroupBox(NovoEquipamento)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 50, 480, 141))
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 20, 480, 116))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.equipamentoNome = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.equipamentoNome.setObjectName("equipamentoNome")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.equipamentoNome
        )
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.equipamentoPotencia = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.equipamentoPotencia.setObjectName("equipamentoPotencia")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.equipamentoPotencia
        )
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.equipamentoFP = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.equipamentoFP.setObjectName("equipamentoFP")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.FieldRole, self.equipamentoFP
        )
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.equipamentoUso = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.equipamentoUso.setObjectName("equipamentoUso")
        self.formLayout.setWidget(
            3, QtWidgets.QFormLayout.FieldRole, self.equipamentoUso
        )
        self.line = QtWidgets.QFrame(NovoEquipamento)
        self.line.setGeometry(QtCore.QRect(10, 200, 480, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayoutWidget = QtWidgets.QWidget(NovoEquipamento)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 220, 470, 25))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout.addItem(spacerItem)
        self.criarEquipamento = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.criarEquipamento.setObjectName("criarEquipamento")
        self.horizontalLayout.addWidget(self.criarEquipamento)
        self.cancelarEquipamento = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancelarEquipamento.setObjectName("cancelarEquipamento")
        self.horizontalLayout.addWidget(self.cancelarEquipamento)

        self.retranslateUi(NovoEquipamento)
        QtCore.QMetaObject.connectSlotsByName(NovoEquipamento)

    def retranslateUi(self, NovoEquipamento):
        _translate = QtCore.QCoreApplication.translate
        NovoEquipamento.setWindowTitle(
            _translate("NovoEquipamento", "Novo Equipamento")
        )
        self.groupBox.setTitle(_translate("NovoEquipamento", "Equipamento"))
        self.label_5.setText(
            _translate(
                "NovoEquipamento", "Equipamento elétrico/iluminação de um ambiente"
            )
        )
        self.groupBox_2.setTitle(_translate("NovoEquipamento", "Parâmetros"))
        self.label.setText(_translate("NovoEquipamento", "Nome"))
        self.label_2.setText(_translate("NovoEquipamento", "Potência "))
        self.label_3.setText(_translate("NovoEquipamento", "Fator de Potência"))
        self.label_4.setText(_translate("NovoEquipamento", "Uso Diário"))
        self.criarEquipamento.setText(_translate("NovoEquipamento", "OK"))
        self.cancelarEquipamento.setText(_translate("NovoEquipamento", "Cancelar"))

    def set_connections(self, MainWindow):
        self.criarEquipamento.clicked.connect(self.create_equipament)
        self.cancelarEquipamento.clicked.connect()

    def create_equipament(self):

        try:
            self.service.inserir_equipamento(
                {
                    "Nome": self.equipamentoNome.text(),
                    "Potencia": self.equipamentoPotencia.text(),
                    "FatorPotencia": self.equipamentoFP.text(),
                    "Uso": self.equipamentoUso.text(),
                }
            )
        except Exception as e:
            print(e)


