# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/joaocaires/Documentos/Projetos/Pessoal/Python/simuload/simuload/user_interface/original_design/cargaMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MenuCarga(object):
    def setupUi(self, MenuCarga):
        MenuCarga.setObjectName("MenuCarga")
        MenuCarga.resize(400, 300)
        self.verticalLayoutWidget = QtWidgets.QWidget(MenuCarga)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 381, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.procuraCarga = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.procuraCarga.setObjectName("procuraCarga")
        self.horizontalLayout_2.addWidget(self.procuraCarga)
        self.procurarBotao = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.procurarBotao.setObjectName("procurarBotao")
        self.horizontalLayout_2.addWidget(self.procurarBotao)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.cargaLista = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.cargaLista.setObjectName("cargaLista")
        self.verticalLayout.addWidget(self.cargaLista)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ExcluirCarga = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ExcluirCarga.setObjectName("ExcluirCarga")
        self.horizontalLayout.addWidget(self.ExcluirCarga)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.NovaCarga = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.NovaCarga.setObjectName("NovaCarga")
        self.horizontalLayout.addWidget(self.NovaCarga)
        self.EditarCarga = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.EditarCarga.setObjectName("EditarCarga")
        self.horizontalLayout.addWidget(self.EditarCarga)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(MenuCarga)
        QtCore.QMetaObject.connectSlotsByName(MenuCarga)

    def retranslateUi(self, MenuCarga):
        _translate = QtCore.QCoreApplication.translate
        MenuCarga.setWindowTitle(_translate("MenuCarga", "Cargas"))
        self.procurarBotao.setText(_translate("MenuCarga", "Procurar"))
        self.ExcluirCarga.setText(_translate("MenuCarga", "Excluir"))
        self.NovaCarga.setText(_translate("MenuCarga", "Criar Nova"))
        self.EditarCarga.setText(_translate("MenuCarga", "Editar"))
