# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/joaocaires/Documentos/Projetos/Pessoal/Python/simuload/simuload/user_interface/original_design/curva_config.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CurvaConfig(object):
    def setupUi(self, CurvaConfig):
        CurvaConfig.setObjectName("CurvaConfig")
        CurvaConfig.resize(264, 248)
        self.buttonBox = QtWidgets.QDialogButtonBox(CurvaConfig)
        self.buttonBox.setGeometry(QtCore.QRect(30, 210, 221, 32))
        font = QtGui.QFont()
        font.setFamily("Reem Kufi")
        font.setPointSize(12)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(CurvaConfig)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 40, 231, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bt_cinco = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Reem Kufi")
        font.setPointSize(12)
        self.bt_cinco.setFont(font)
        self.bt_cinco.setObjectName("bt_cinco")
        self.verticalLayout.addWidget(self.bt_cinco)
        self.bt_quinze = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Reem Kufi")
        font.setPointSize(12)
        self.bt_quinze.setFont(font)
        self.bt_quinze.setObjectName("bt_quinze")
        self.verticalLayout.addWidget(self.bt_quinze)
        self.bt_trinta = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Reem Kufi")
        font.setPointSize(12)
        self.bt_trinta.setFont(font)
        self.bt_trinta.setObjectName("bt_trinta")
        self.verticalLayout.addWidget(self.bt_trinta)
        self.bt_hora = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Reem Kufi")
        font.setPointSize(12)
        self.bt_hora.setFont(font)
        self.bt_hora.setObjectName("bt_hora")
        self.verticalLayout.addWidget(self.bt_hora)
        self.label = QtWidgets.QLabel(CurvaConfig)
        self.label.setGeometry(QtCore.QRect(20, 10, 158, 21))
        font = QtGui.QFont()
        font.setFamily("Reem Kufi")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(CurvaConfig)
        self.buttonBox.accepted.connect(CurvaConfig.accept)
        self.buttonBox.rejected.connect(CurvaConfig.reject)
        QtCore.QMetaObject.connectSlotsByName(CurvaConfig)

    def retranslateUi(self, CurvaConfig):
        _translate = QtCore.QCoreApplication.translate
        CurvaConfig.setWindowTitle(_translate("CurvaConfig", "Dialog"))
        self.bt_cinco.setText(_translate("CurvaConfig", "5 minutos"))
        self.bt_quinze.setText(_translate("CurvaConfig", "15 minutos"))
        self.bt_trinta.setText(_translate("CurvaConfig", "30 minutos"))
        self.bt_hora.setText(_translate("CurvaConfig", "1 hora"))
        self.label.setText(_translate("CurvaConfig", "Intervalos:"))
